name: Ejemplo Deploy 🎉

on: push

jobs:
  first_job:
    name: Declarando el servidor
    runs-on: ubuntu-latest

    steps:
      - name: mostrar directorio
        run: ls -la
      
      - name: Action
        uses: actions/checkout@v4
        
      - name: mostrar directorio
        run: ls -la

  second_job:
    name: Ejecutando checkout
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Despedirse
        run: echo "Adios mundo"
