name: Ejemplo Deploy 🎉

on: push

jobs:
  first_job:
    name: Primer
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Ejemplo de Variable
        id: step_1  
        run: echo "my_variable=Te amo con todo mi corazón" >> $GITHUB_OUTPUT
      
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"
        
      - name: mostrar directorio
        run: ls -la

  second_job:
    name: Ejemplo de hola mundo
    needs: first_job
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}

    steps:
      - name: Saludo a mi amor
        run: echo "$SALIDA"
