name: Ejemplo Deploy 🎉

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        run: echo "Hola mundo"

  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Despedirse
        run: echo "Adios mundo"
