name: Ejemplo Deploy 🎉

on: push

jobs:
  first_job:
    name: Primera ejecución
    runs-on: ubuntu-latest

    steps:
      - name: Generar archivo
        id: step_1  
        run: |
         echo "Archivo prueba, Hola" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log
    
  second_job:
    name: Segunda ejecución
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Mostrar contenido del archivo
        run: |
          cat test.log