name: Ejemplo Deploy 🎉

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        run: echo "Hola mundo"

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Despedirse
        run: echo "Adios mundo"
