name: Ejemplo Deploy 🎉

on: push

jobs:
  first_job:
    name: Primera ejecución
    runs-on: ubuntu-latest

    steps:
      - name: Generar archivo
        id: step_1  
        run: |
         echo "Archivo prueba, Hola" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log
      
